#!/bin/sh

composer analyse
PHP_STAN_EXIT_CODE=$?


if [ $PHP_STAN_EXIT_CODE -ne 0 ]
then
    exit -1
fi


CS_FIXER_EXIT_CODE=$?

if [ $CS_FIXER_EXIT_CODE -ne 0 ]
then
    composer composer cs-check
fi
