<?php

declare(strict_types=1);

namespace App\Services;

use App\Exceptions\BusinessException;

class DistrictService
{
    private static array $districts = [
        'andijan' => [
                'body_ru' => [
                        'Алтынкульский район',
                        'Андижанский район',
                        'Асакинский район',
                        'Балыкчинский район',
                        'Бозский район',
                        'Булакбашинский район',
                        'Джалакудукский район',
                        'Избасканский район',
                        'Кургантепинский район',
                        'Мархаматский район',
                        'Пахтаабадский район',
                        'Улугнорский район',
                        'Ходжаабадский район',
                        'Шахриханский район',
                        'город Андижан',
                        'город Ханабад',
                    ],
                'body_uz' => [
                        'Oltinko’l tumani',
                        'Andijon tumani',
                        'Asaka tumani',
                        'Baliqchi tumani',
                        'Bo’z tumani',
                        'Buloqboshi tumani',
                        'Jalaquduq tumani',
                        'Izboskan tumani',
                        'Qo’rg’ontepa tumani',
                        'Marhamat tumani',
                        'Paxtaobod tumani',
                        'Ulug’nor tumani',
                        'Xo’jaobod tumani',
                        'Shahrixon tumani',
                        'Andijon shahri',
                        'Xonobod shahri',
                    ],
            ],
        'bukhara' => [
                'body_ru' => [
                        'Алатский район',
                        'Бухарский район',
                        'Вабкентский район',
                        'Гиждуванский район',
                        'Жондорский район',
                        'Каганский район',
                        'Каракульский район',
                        'Караулбазарский район',
                        'Пешкунский район',
                        'Ромитанский район',
                        'Шафирканский район',
                        'город Бухара',
                        'город Каган',
                    ],
                'body_uz' => [
                        'Olot tumani',
                        'Buxoro tumani',
                        'Vobkent tumani',
                        'G’ijduvon tumani',
                        'Jondor tumani',
                        'Kogon tumani',
                        'Qorako’l tumani',
                        'Qorovulbozor tumani',
                        'Peshku tumani',
                        'Romitan tumani',
                        'Shofirkon tumani',
                        'Buxoro shahri',
                        'Kogon shahri',
                    ],
            ],
        'jizzakh' => [
                'body_ru' => [
                        'Арнасайский район',
                        'Бахмальский район',
                        'Галляаральский район',
                        'Дустликский район',
                        'Зааминский район',
                        'Зарбдарский район',
                        'Зафарабадский район',
                        'Мирзачульский район',
                        'Пахтакорский район',
                        'Фаришский район',
                        'Шараф-Рашидовский район',
                        'Янгиабадский район',
                        'город Джизак',
                    ],
                'body_uz' => [
                        'Arnasoy tumani',
                        'Baxmal tumani',
                        'G`allaorol tumani',
                        'Do`stlik tumani',
                        'Zomin tumani',
                        'Zarbdor tumani',
                        'Zafarobod tumani',
                        'Mirzacho`l tumani',
                        'Paxtakor tumani',
                        'Forish tumani',
                        'Sharof Rashidov tumani',
                        'Yangiobod tumani',
                        'Jizzax shahri',
                    ],
            ],
        'qashqadaryo' => [
                'body_ru' => [
                        'Гузарский район',
                        'Дехканабадский район',
                        'Камашинский район',
                        'Каршинский район',
                        'Касанский район',
                        'Касбийский район',
                        'Китабский район',
                        'Миришкорский район',
                        'Мубарекский район',
                        'Нишанский район',
                        'Чиракчинский район',
                        'Шахрисабзский район',
                        'Яккабагский район',
                        'город Карши',
                    ],
                'body_uz' => [
                        'G’uzor tumani',
                        'Dehqonobod tumani',
                        'Qamashi tumani',
                        'Qarshi tumani',
                        'Koson tumani',
                        'Kasbi tumani',
                        'Kitob tumani',
                        'Mirishkor tumani',
                        'Muborak tumani',
                        'Nishon tumani',
                        'Chiroqchi tumani',
                        'Shahrisabz tumani',
                        'Yakkabog’ tumani',
                        'Qarshi shahri',
                    ],
            ],
        'navoiy' => [
                'body_ru' => [
                        'Канимехский район',
                        'Карманинский район',
                        'Кызылтепинский район',
                        'Навбахорский район',
                        'Нуратинский район',
                        'Тамдынский район',
                        'Учкудукский район',
                        'Хатырчинский район',
                        'город Зарафшан',
                        'город Навои',
                    ],
                'body_uz' => [
                        'Konimex tumani',
                        'Karman tumani',
                        'Qiziltepa tumani',
                        'Navbahor tumani',
                        'Nurota tumani',
                        'Tomdi tumani',
                        'Uchquduq tumani',
                        'Xatirchi tumani',
                        'Zarafshon shahri',
                        'Navoiy shahri',
                    ],
            ],
        'namangan' => [
                'body_ru' => [
                        'Касансайский район',
                        'Мингбулакский район',
                        'Наманганский район',
                        'Нарынский район',
                        'Папский район',
                        'Туракурганский район',
                        'Уйчинский район',
                        'Учкурганский район',
                        'Чартакский район',
                        'Чустский район',
                        'Янгикурганский район',
                        'город Наманган',
                    ],
                'body_uz' => [
                        'Kosonsoy tumani',
                        'Mingbuloq tumani',
                        'Namangan tumani',
                        'Norin tumani',
                        'Pop tumani',
                        'To’raqo’rg’on tumani',
                        'Uychi tumani',
                        'Uchqo’rg’on tumani',
                        'Chortoq tumani',
                        'Chust tumani',
                        'Yangiqo’rg’on tumani',
                        'Namangan shahri',
                    ],
            ],
        'samarkand' => [
                'body_ru' => [
                        'Акдарьинский район',
                        'Булунгурский район',
                        'Джамбайский район',
                        'Иштыханский район',
                        'Каттакурганский район',
                        'Кошрабадский район',
                        'Нарпайский район',
                        'Нурабадский район',
                        'Пайарыкский район',
                        'Пастдаргомский район',
                        'Пахтачийский район',
                        'Самаркандский район',
                        'Тайлакский район',
                        'Ургутский район',
                        'город Каттакурган',
                        'город Самарканд',
                    ],
                'body_uz' => [
                        'Oqdaryo tumani',
                        'Bulung’ur tumani',
                        'Jomboy tumani',
                        'Ishtixon tumani',
                        'Kattaqoʻrgʻon tumani',
                        'Qoʻshrabot tumani',
                        'Narpay tumani',
                        'Nurobod tumani',
                        'Payariq tumani',
                        'Pastdargʻom tumani',
                        'Paxtachi tumani',
                        'Samarqand tumani',
                        'Toyloq tumani',
                        'Urgut tumani',
                        'Kattaqo’rg’on shahri',
                        'Samarqand shahri',
                    ],
            ],
        'surxondaryo' => [
                'body_ru' => [
                        'Алтынсайский район',
                        'Ангорский район',
                        'Байсунский район',
                        'Бандиханский район',
                        'Денауский район',
                        'Джаркурганский район',
                        'Кизирикский район',
                        'Кумкурганский район',
                        'Музрабадский район',
                        'Сариасийский район',
                        'Термезский район',
                        'Узунский район',
                        'Шерабадский район',
                        'Шурчинский район',
                        'город Термез',
                    ],
                'body_uz' => [
                        'Oltinsoy tumani',
                        'Angor tumani',
                        'Boysun tumani',
                        'Bandihon tumani',
                        'Denov tumani',
                        'Jarqoʻrgʻon tumani',
                        'Qiziriq tumani',
                        'Qumqoʻrgʻon tumani',
                        'Muzrabot tumani',
                        'Sariosiyo tumani',
                        'Termiz tumani',
                        'Uzun tumani',
                        'Sherobod tumani',
                        'Shoʻrchi tumani',
                        'Termiz shahri',
                    ],
            ],
        'sirdarya' => [
                'body_ru' => [
                        'Акалтынский район',
                        'Баяутский район',
                        'Гулистанский район',
                        'Мирзаабадский район',
                        'Сайхунабадский район',
                        'Сардобский район',
                        'Сырдарьинский район',
                        'Хавастский район',
                        'город Гулистан',
                        'город Ширин',
                        'город Янгиер',
                    ],
                'body_uz' => [
                        'Oqoltin tumani',
                        'Boyovut tumani',
                        'Guliston tumani',
                        'Mirzaobod tumani',
                        'Sayxunobod tumani',
                        'Sardoba tumani',
                        'Sirdaryo tumani',
                        'Xovos tumani',
                        'Guliston shahri',
                        'Shirin shahri',
                        'Yangiyer shahri',
                    ],
            ],
        'tashkent' => [
                'body_ru' => [
                        'Аккурганский район',
                        'Ахангаранский район',
                        'Бекабадский район',
                        'Бостанлыкский район',
                        'Букинский район',
                        'Зангиатинский район',
                        'Кибрайский район',
                        'Куйичирчикский район',
                        'Паркентский район',
                        'Пскентский район',
                        'Ташкентский район',
                        'Уртачирчикский район',
                        'Чиназский район',
                        'Юкоричирчикский район',
                        'Янгиюльский район',
                        'город Алмалык',
                        'город Ангрен',
                        'город Бекабад',
                        'город Чирчик',
                    ],
                'body_uz' => [
                        'Oqqoʻrgʻon tumani',
                        'Ohangaron tumani',
                        'Bekobod tumani',
                        'Boʻstonliq tumani',
                        'Boʻka tumani',
                        'Zangiota tumani',
                        'Qibray tumani',
                        'Quyichirchiq tumani',
                        'Parkent tumani',
                        'Piskent tumani',
                        'Toshkent tumani',
                        'Oʻrtachirchiq tumani',
                        'Chinoz tumani',
                        'Yuqorichirchiq tumani',
                        'Yangiyoʻl tumani',
                        'Olmaliq shahri',
                        'Angren shahri',
                        'Bekobod shahri',
                        'Chirchiq shahri',
                    ],
            ],
        'fergana' => [
                'body_ru' => [
                        'Алтыарыкский район',
                        'Багдадский район',
                        'Бешарыкский район',
                        'Бувайдинский район',
                        'Дангаринский район',
                        'Кувинский район',
                        'Куштепинский район',
                        'Риштанский район',
                        'Сохский район',
                        'Ташлакский район',
                        'Узбекистанский район',
                        'Учкуприкский район',
                        'Ферганский район',
                        'Фуркатский район',
                        'Язъяванский район',
                        'город Коканд',
                        'город Кувасай',
                        'город Маргилан',
                        'город Фергана',
                    ],
                'body_uz' => [
                        'Oltiariq tumani',
                        'Bagʻdod tumani',
                        'Beshariq tumani',
                        'Buvayda tumani',
                        'Dangʻara tumani',
                        'Quva tumani',
                        'Qoʻshtepa tumani',
                        'Rishton tumani',
                        'Soʻx tumani',
                        'Toshloq tumani',
                        'Oʻzbekiston tumani',
                        'Uchkoʻprik tumani',
                        'Fargʻona tumani',
                        'Furqat tumani',
                        'Yozyovon tumani',
                        'Qoʻqon shahri',
                        'Quvasoy shahri',
                        'Marg’ilon shahri',
                        'Fargʻona shahri',
                    ],
            ],
        'xorazm' => [
                'body_ru' => [
                        'Багатский район',
                        'Гурленский район',
                        'Кошкупырский район',
                        'Ургенчский район',
                        'Хазараспский район',
                        'Ханкинский район',
                        'Хивинский район',
                        'Шаватский район',
                        'Янгиарыкский район',
                        'Янгибазарский район',
                        'город Ургенч',
                    ],
                'body_uz' => [
                        'Bogʻot tumani',
                        'Gurlan tumani',
                        'Qoʻshkoʻpir tumani',
                        'Urganch tumani',
                        'Xazorasp tumani',
                        'Xonqa tumani',
                        'Xiva tumani',
                        'Shovot tumani',
                        'Yangiariq tumani',
                        'Yangibozor tumani',
                        'Urganch shahri',
                    ],
            ],
        'karakalpakstan' => [
                'body_ru' => [
                        'Амударьинский район',
                        'Берунийский район',
                        'Караузякский район',
                        'Кегейлийский район',
                        'Кунградский район',
                        'Канлыкульский район',
                        'Муйнакский район',
                        'Нукусский район',
                        'Тахиаташский район',
                        'Тахтакупырский район',
                        'Турткульский район',
                        'Ходжейлийский район',
                        'Чимбайский район',
                        'Шуманайский район',
                        'Элликкалинский район',
                        'город Нукус',
                    ],
                'body_uz' => [
                        'Amudaryo tumani',
                        'Beruniy tumani',
                        'Qoraoʻzak tumani',
                        'Kegeyli tumani',
                        'Qoʻngʻirot tumani',
                        'Qanlikoʻl tumani',
                        'Moʻynoq tumani',
                        'Nukus tumani',
                        'Taxiatosh tumani',
                        'Taxtakoʻpir tumani',
                        'Toʻrtkoʻl tumani',
                        'Xoʻjayli tumani',
                        'Chimboy tumani',
                        'Shumanay tumani',
                        'Ellikqala tumani',
                        'Nukus shahri',
                    ],
            ],
        'tashkent_city' => [
                'body_ru' => [
                        'Алмазарский район',
                        'Бектемирский район',
                        'Мирабадский район',
                        'Мирзо-Улугбекский район',
                        'Сергелийский район',
                        'Учтепинский район',
                        'Яшнабадский район',
                        'Чиланзарский район',
                        'Шайхантахурский район',
                        'Юнусабадский район',
                        'Яккасарайский район',
                    ],
                'body_uz' => [
                        'Olmazor tumani',
                        'Bektemir tumani',
                        'Mirobod tumani',
                        'Mirzo Ulug’bek tumani',
                        'Sirg’ali tumani',
                        'Uchtepa tumani',
                        'Xamza tumani',
                        'Chilonzor tumani',
                        'Shayxontoxur tumani',
                        'Yunusobod tumani',
                        'Yakkasaroy tumani',
                    ],
            ],
    ];

    public static function getDistricts(): array
    {
        return self::$districts;
    }

    public static function getDistrictsByRegion(string $region): array
    {
        if (empty(self::$districts[$region])) {
            throw new BusinessException('Данный район не был найден', 'object_not_found', 404);
        }

        return self::$districts[$region];
    }
}
