---
stages:
  - before-build
  - build
  - test

variables:
  PHP_IMAGE: $CI_REGISTRY/images/php:8.0-fpm-infra

Composer Install:
  stage: before-build
  image: $PHP_IMAGE
  script:
    - git config --global gitlab.accesstoken $CI_JOB_TOKEN
    - composer config gitlab-domains $CI_SERVER_HOST
    - composer config gitlab-token.$CI_SERVER_HOST $CI_JOB_TOKEN
    - composer i
  artifacts:
    paths:
      - vendor
    expire_in: 1 day
  only:
    - master

Build:
  stage: build
  image: docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --no-cache --pull -f infra/production/Dockerfile -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master
  tags:
    - cicd
    - shell

Static-analyze:
  stage: test
  image: docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker run --rm $CI_REGISTRY_IMAGE:latest ./vendor/bin/phpstan analyse --memory-limit=2G --configuration='infra/config/phpstan.neon'
  only:
    - master
  tags:
    - cicd
    - shell

Check-CS-Fixer:
  stage: test
  image: docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker run --rm $CI_REGISTRY_IMAGE:latest ./vendor/bin/php-cs-fixer fix -vvv --dry-run --show-progress=dots --config=./infra/config/.php-cs-fixer.php --allow-risky=yes
  only:
    - master
  tags:
    - cicd
    - shell

