stages:
  - build-docker

variables:
  DOCKER_TLS_CERTDIR: ""
##  DOCKER_HOST: tcp://docker:2376
#  DOCKER_TLS_CERTDIR: "/certs"
#  DOCKER_TLS_VERIFY: 0
#  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"


#cache:
#  key: ${CI_COMMIT_REF_SLUG}
#  paths:
#    - vendor/

build-master-docker:
  stage: build-docker
  image: docker:19.03.13
  services:
    - docker:dind
  before_script:
    - echo $CI_REGISTRY
    - until docker info; do sleep 1; done
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

  script:
    - docker build --pull -t "$CI_REGISTERY_IMAGE" .
    - docker push "$CI_REGISTERY_IMAGE"
