stages:
  - build-docker

variables:
  DOCKER_TLS_CERTDIR: ""
  PHP_IMAGE: ginger.alifshop.uz:443/images/php:8.0-fpm-infra


cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/

build-master-docker:
  stage: build-docker
  image: docker:19.03.13
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

  script:
    - docker build --pull -t $PHP_IMAGE .
    - docker push $PHP_IMAGE
    - composer i
