---
stages:
  - build
  - test

variables:
  PHP_IMAGE: $CI_REGISTRY/images/php:8.0-fpm-infra

Composer Install:
  stage: build
  image: $PHP_IMAGE
  script:
    - git config --global gitlab.accesstoken $CI_JOB_TOKEN
    - composer config gitlab-domains $CI_SERVER_HOST
    - composer config gitlab-token.$CI_SERVER_HOST $CI_JOB_TOKEN
    - composer i
#  tags:
#    - cicd
#    - shell

  artifacts:
    paths:
      - vendor
    expire_in: 1 day

Static-analyze:
  stage: test
  image: $PHP_IMAGE
  script:
    - ./vendor/bin/phpstan analyse --memory-limit=2G --configuration='infra/config/phpstan.neon'

Check-CS-Fixer:
  stage: test
  image: $PHP_IMAGE
  script:
    - ./vendor/bin/php-cs-fixer fix -vvv --dry-run --show-progress=dots --config=./infra/config/.php-cs-fixer.php --allow-risky=yes

