stages:
  - build-docker

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"


#cache:
#  key: ${CI_COMMIT_REF_SLUG}
#  paths:
#    - vendor/

build-master-docker:
  stage: build-docker
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - echo 123
#    - docker build --pull -t "$CI_REGISTERY_IMAGE" .
#    - docker push "$CI_REGISTERY_IMAGE"
