version: '3'
services:
  app:
    build:
      args:
        user: docker
        uid: 1000
      context: .
      dockerfile: docker/local/php/Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www


