version: "3.7"

services:
  app:
    container_name: alif-service-merchant-app
    build:
      dockerfile: Dockerfile
      context: ./php/
    volumes:
      - ../../:/app
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
    ports:
      - 127.0.4.1:9000:9000
    depends_on:
      - redis
      - mongodb
  nginx:
    container_name: alif-service-merchant-nginx
    image: $IMAGE_NGINX
    volumes:
      - ../../:/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 127.0.4.1:80:80
    depends_on:
      - app
  redis:
    container_name: alif-service-merchant-redis
    image: $IMAGE_REDIS
    ports:
      - 127.0.4.1:6379:6379
  mongodb:
    container_name: alif-service-merchant-mongodb
    image: $IMAGE_MONGODB
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    ports:
      - 127.0.4.1:27017:27017
    volumes:
      - alif_mongodb:/data/db
  mysql:
    container_name: alif-service-merchant-mysql
    image: $IMAGE_MYSQL
    ports:
      - 127.0.4.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    volumes:
      - alif_mysql:/var/lib/mysql

volumes:
  alif_mongodb:
  alif_mysql:

