version: "3.7"

services:
  app:
    image: $APP_IMAGE_NAME
    container_name: $APP_CONTAINER_NAME
    build:
      dockerfile: Dockerfile
      context: ./php/
    volumes:
      - ../../:/app
#      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.override.conf:ro
      - ./php/php.ini:/usr/local/etc/php/conf.d/php-override.ini:ro
      - ./supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - 127.0.4.1:9000:9000
    environment:
      - DEV_UID=$DEV_UID
    depends_on:
      - redis

  supervisor:
    image: $APP_IMAGE_NAME
    container_name: $SUPERVISOR_CONTAINER_NAME
    build:
      dockerfile: Dockerfile
      context: ./php/
    volumes:
      - ../../:/app
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.override.conf:ro
      - ./php/php.ini:/usr/local/etc/php/conf.d/php-override.ini:ro
      - ./supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    entrypoint: ["supervisord", "-c", "/etc/supervisor/supervisord.conf"]
    depends_on:
      - redis

  nginx:
    container_name: $NGINX_CONTAINER_NAME
    image: $IMAGE_NGINX
    volumes:
      - ../../:/app
      - ./nginx/templates:/etc/nginx/templates
    ports:
      - 127.0.4.1:80:80
    environment:
      - APP_CONTAINER_NAME=$APP_CONTAINER_NAME
    depends_on:
      - app
  redis:
    container_name: $REDIS_CONTAINER_NAME
    image: $IMAGE_REDIS
    ports:
      - 127.0.4.1:6379:6379

networks:
  default:
    external:
      name: alif-infra
