version: "3.7"

services:
  app:
    container_name: alif-service-merchant-app
    build:
      dockerfile: Dockerfile
      context: ./php/
    volumes:
      - ../../:/app
    depends_on:
      - redis
      - mongodb
  nginx:
    container_name: alif-service-merchant-nginx
    image: $IMAGE_NGINX
    volumes:
      - ../../:/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 127.0.4.1:80:80
    depends_on:
      - app
  redis:
    container_name: alif-service-merchant-redis
    image: $IMAGE_REDIS
    ports:
      - 127.0.4.1:6379:6379
  mongodb:
    container_name: alif-service-merchant-mongodb
    image: $IMAGE_MONGODB
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    ports:
      - 127.0.4.1:27017:27017
