#!/bin/sh

if [ -f "infra/local/.env" ]; then
    export $(cat "infra/local/.env" | sed 's/#.*//g' | xargs)
fi

if [ ! "$(docker ps -q -f name="${ALIF_INFRA_DB}")"  ]; then
	echo "First you need to start the ${ALIF_INFRA_DB} container"
	exit 0;
fi
docker exec "${ALIF_INFRA_DB}" mysql -u root -p"${ALIF_INFRA_DB_PASSWORD}" -e "CREATE DATABASE ${ALIF_INFRA_DB_DATABASE}"
